title:             Justudios  
email:             justin@justudios.com
description:       Justudios - Web Developer & Furniture Maker
author:            Justin Flowers
baseurl:           "/justudios"
url:               "http://zadees.github.io"

# Social Profiles
twitter_username:  StudiosJustin
github_username:   zadees

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
